<div style="background:linear-gradient(135deg,#14b8a6 0%,#6366f1 100%);color:#ffffff;padding:26px 30px;border-radius:16px;font-family:'Segoe UI',Arial,sans-serif;">
  <div style="letter-spacing:.18em;font-size:12px;text-transform:uppercase;opacity:.85;">DS Elective 4 &nbsp;•&nbsp; Deep Learning</div>
  <div style="font-size:30px;font-weight:700;margin:6px 0 2px;">Laboratory Task 5</div>
  <div style="font-size:18px;opacity:.95;">PyTorch Tensor Basics</div>
  <div style="font-size:13px;opacity:.8;margin-top:10px;">Creating, converting, reshaping, indexing and multiplying tensors</div>
</div>

**Name:** Edrian C. Jugan

# Task 5: PyTorch Tensor Basics

## 📌 Problem Statement

1. Perform standard imports
2. Create a function called `set_seed()` that accepts `seed: int`, returns nothing, and just sets the seed
3. Create a NumPy array called `arr` with 6 random integers between 0 (inclusive) and 5 (exclusive); call `set_seed()` with `42`
4. Create a tensor `x` from the array
5. Change the dtype of `x` from `int32` to `int64`
6. Reshape `x` into a 3x2 tensor
7. Return the right-hand column of tensor `x`
8. Without changing `x`, return a tensor of square values of `x`
9. Create a tensor `y` with the same number of elements as `x` that can be matrix-multiplied with `x` (use PyTorch directly, seed 42, random integers from 0 to 4)
10. Find the matrix product of `x` and `y`

## 🗺️ Overview

| # | What we do | Result |
|---|---|---|
| 3 | `arr` (seed 42) | `[3 4 2 4 4 1]` (`int32`) |
| 4 | `torch.from_numpy(arr)` | 1-D tensor with 6 elements |
| 5 | `x.type(torch.int64)` | dtype becomes `torch.int64` |
| 6 | `x.reshape(3, 2)` | `[[3, 4], [2, 4], [4, 1]]` |
| 7 | `x[:, 1]` | `[4, 4, 1]` |
| 8 | `x ** 2` | `[[9, 16], [4, 16], [16, 1]]` |
| 9 | `y` must be **2 × 3** | `[[2, 2, 1], [4, 1, 0]]` |
| 10 | `x @ y` | 3 × 3 matrix `[[22, 10, 3], [20, 8, 2], [12, 9, 4]]` |

## 1️⃣ Standard imports

In [1]:
import random
import numpy as np
import torch

## 2️⃣ The `set_seed()` function
It takes an integer, sets the seed for Python, NumPy and PyTorch, and returns nothing.

In [2]:
def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

## 3️⃣ Create the NumPy array `arr`
6 random integers from 0 (inclusive) to 5 (exclusive), with seed `42`. We pass `dtype=np.int32` so the array really is `int32` (the default integer type changes depending on the operating system).

In [3]:
set_seed(42)
arr = np.random.randint(0, 5, size=6, dtype=np.int32)
print(arr)
print(arr.dtype)

[3 4 2 4 4 1]
int32


## 4️⃣ Create the tensor `x` from the array
`torch.from_numpy()` shares memory with the array and keeps its dtype (`int32`).

In [4]:
x = torch.from_numpy(arr)
print(x)
print(x.dtype)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
torch.int32


## 5️⃣ Change the dtype from `int32` to `int64`

In [5]:
print('Old:', x.type())

x = x.type(torch.int64)   # same as x.to(torch.int64) or x.long()

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


## 6️⃣ Reshape `x` into a 3×2 tensor
There are several ways: `reshape()`, `view()`, `view()` with `-1`, or `view_as()`.

In [6]:
x = x.reshape(3, 2)        # option 1
print(x)

print(x.view(3, 2))        # option 2
print(x.view(-1, 2))       # option 3: -1 lets PyTorch figure out the rows
print(x.view_as(torch.zeros(3, 2)))   # option 4

tensor([[3, 4],
        [2, 4],
        [4, 1]])
tensor([[3, 4],
        [2, 4],
        [4, 1]])
tensor([[3, 4],
        [2, 4],
        [4, 1]])
tensor([[3, 4],
        [2, 4],
        [4, 1]])


## 7️⃣ Return the right-hand column of `x`

In [7]:
x[:, 1]

tensor([4, 4, 1])

If we want to keep it as a column with shape `(3, 1)` instead, use `x[:, 1:]`.

In [8]:
x[:, 1:]

tensor([[4],
        [4],
        [1]])

## 8️⃣ Square values of `x` without changing `x`
These all return a **new** tensor, so `x` stays the same (unlike the in-place `x.pow_(2)` or `x.square_()`).

In [9]:
print(x ** 2)           # option 1
print(torch.pow(x, 2))  # option 2
print(x.pow(2))         # option 3
print(torch.square(x))  # option 4
print(x * x)            # option 5

print("\nx is unchanged:")
print(x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

x is unchanged:
tensor([[3, 4],
        [2, 4],
        [4, 1]])


## 9️⃣ Create `y` so it can be matrix-multiplied with `x`

For $A(m\times n)\cdot B(n\times p)$ to work, the columns of $A$ must equal the rows of $B$.

- `x` is $3\times2$ and has 6 elements.
- So `y` needs **2 rows**. To also have 6 elements, it must be $2\times3$.

We use `torch.randint` directly (not NumPy) with seed 42 and values from 0 to 4.

In [10]:
set_seed(42)
y = torch.randint(0, 5, (2, 3))
print(y)
print(y.shape)
print(y.numel() == x.numel())

tensor([[2, 2, 1],
        [4, 1, 0]])
torch.Size([2, 3])
True


## 🔟 Matrix product of `x` and `y`

$(3\times2)\cdot(2\times3)=(3\times3)$. Both tensors are `int64`, so the multiplication works (this is why step 5 mattered).

In [11]:
result = x @ y             # same as torch.mm(x, y) or x.matmul(y)
print(result)
print(result.shape)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
torch.Size([3, 3])


## ✅ Final Answers

| Step | Answer |
|---|---|
| `arr` | $[3,4,2,4,4,1]$ |
| `x` (3×2, `int64`) | $\begin{bmatrix}3&4\\2&4\\4&1\end{bmatrix}$ |
| Right-hand column | $[4,\;4,\;1]$ |
| Squares of `x` | $\begin{bmatrix}9&16\\4&16\\16&1\end{bmatrix}$ |
| `y` (2×3) | $\begin{bmatrix}2&2&1\\4&1&0\end{bmatrix}$ |
| `x @ y` | $\begin{bmatrix}22&10&3\\20&8&2\\12&9&4\end{bmatrix}$ |